name: Sphinx build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build HTML
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: doc

    - run: sudo rm -rf build/html/_sources

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: ${{ github.ref == 'refs/heads/master' }}
      with:
        name: html-docs
        path: |
          doc/build/html/
          !doc/build/html/_sources

    - name: Deploy HTML
      uses: peaceiris/actions-gh-pages@v4
      if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: doc/build/html
